/*

amusing pictures triggered by steps, no use, no step counts shown.

*/


// pictures

var w1 = `
.........XX.....
......XXXXX.....
.....XXXXX......
......XX.X......
......XXXXX.....
......XXXX......
.......XX.......
......XXXX......
.....XX.XXX.....
.....XX.XXX.....
.....XX.XXX.....
.....XXX.XX.....
......XXXX......
.......XX.......
.......XX.......
.......XXX......
`;

var w2 = `
.........XX.....
......XXXXX.....
.....XXXXX......
......XX.X......
......XXXXX.....
......XXXX......
.......XX.......
......XXXX......
.....XXXXXX.....
.....XXXXXX.....
....XXXX.XXX....
....XXXXX.XX....
......XXXX......
.....XXX.XX.....
.....XX.XXX.....
.....XXX.XXX....
`;

var w3 = `
.........XX.....
......XXXXX.....
.....XXXXX......
......XX.X......
......XXXXX.....
......XXXX......
.......XX.......
......XXXX......
.....XXXXXX.....
....XXXXXXXX....
...XXXXXXXXXX...
...XX.XXXX.XX...
......XXXXX.....
.....XXX.XX.X...
....XX....XXX...
....XXX....X....
`;

// defs 
var scale = 6;
var width = 16;
var height = 16;

g.clear();

var img = new Array(
  Graphics.createImage(w1),
  Graphics.createImage(w2),
  Graphics.createImage(w3), 
  Graphics.createImage(w2)
);

function update() {
 i = Bangle.getStepCount()%4;
  g.drawImage(
    img[i],
    g.getWidth()/2 - width*scale/2,
    g.getHeight()/2 - height*scale/2,
    { "scale": scale}); 
}

update();

// on step draw the willy
Bangle.on("step", ()=> {
  update();
});

// listen for button press, convenience to exit
Bangle.setUI("clock");

/*

require("Storage").write("minerwalk.info", {
  "id": "minerwalk",
  "name": "MinerWalk",
  "src": "minerwalk.js"
});


*/
