/*

amusing pictures triggered by steps, no use, no step counts shown.

*/

{
  // pictures

  var w1 = `
.........XX.....
......XXXXX.....
.....XXXXX......
......XX.X......
......XXXXX.....
......XXXX......
.......XX.......
......XXXX......
.....XX.XXX.....
.....XX.XXX.....
.....XX.XXX.....
.....XXX.XX.....
......XXXX......
.......XX.......
.......XX.......
.......XXX......
`;

  var w2 = `
.........XX.....
......XXXXX.....
.....XXXXX......
......XX.X......
......XXXXX.....
......XXXX......
.......XX.......
......XXXX......
.....XXXXXX.....
.....XXXXXX.....
....XXXX.XXX....
....XXXXX.XX....
......XXXX......
.....XXX.XX.....
.....XX.XXX.....
.....XXX.XXX....
`;

  var w3 = `
.........XX.....
......XXXXX.....
.....XXXXX......
......XX.X......
......XXXXX.....
......XXXX......
.......XX.......
......XXXX......
.....XXXXXX.....
....XXXXXXXX....
...XXXXXXXXXX...
...XX.XXXX.XX...
......XXXXX.....
.....XXX.XX.X...
....XX....XXX...
....XXX....X....
`;

  // defs 
  var scale = 6;
  var width = 16;
  var height = 16;



  var img = new Array(
    Graphics.createImage(w1),
    Graphics.createImage(w2),
    Graphics.createImage(w3),
    Graphics.createImage(w2)
  );


  Bangle.setHRMPower(1);
  g.clear();

  let lastCheck = Date.now();
  let i = 0;
  
  let update = function () {
    console.log("tick");
    i = (i+1) % 4;
    g.drawImage(
      img[i],
      g.getWidth() / 2 - width * scale / 2,
      g.getHeight() / 2 - height * scale / 2,
      { "scale": scale });
  };

  update();

  let timer;
  let pulsePeriod = 0;

  console.log("hello");

  Bangle.on("HRM", function (hrm) {
    if (hrm.bpm > 0) pulsePeriod = 60000 / hrm.bpm;
    console.log(pulsePeriod);
    now = Date.now();
    if ((lastCheck + 5000) < now) {
      if (timer) clearInterval(timer);
      if (pulsePeriod>0) timer = setInterval(update, pulsePeriod/img.length);
      lastCheck = now;
      console.log("new interval "+ pulsePeriod);
    }
  });



  // Show launcher when middle button pressed
  Bangle.setUI({
    mode: "clock", remove: function () {
      if (timer) clearInterval(timer);
      timer = null;
      Bangle.setHRMPower(0);
    }
  });

}
/*

require("Storage").write("minerheart.info", {
  "id": "minerheart",
  "name": "MinerHeart",
  "icon": "minerheart.img",
  "src": "minerheart.js"
});


*/
