{
  
  var face = {
  width : 174, height : 174, bpp : 2,
  transparent : 0,
  buffer : require("heatshrink").decompress(atob("AH4A/AH4Atgf/AAPwFc0/4EAh4sjEgIAE/kP/h8iAAfAmBWB/4qdEgQuB+E//8/GoaICPriuIAgUPFbU/+EwGg7WDLoLcZO4S1IawaEBFbAqKW4QrcFRiwFFa4qNBworWFRwAF+ZcDACEPICi0DACEDS6orTgZrUAAP8CaTuWFac8FSxDShgqXTSLXWAAUPCKDXWAAU/CB8wFTDHQVjDaRVjLaRVjLaQVjSuPVjauOSB6CODpjnOAB0/QNMA/iBLFTsDe5aBdVwILKngqdVxaBeQRnAFb0MEBKBfgHzQNAgBhgKI+ArfhghIQMCCJQMCCKQMCCJWxKCggfAQVMwK0M8EYyBigHDQNBOBJ4yBiEYPwKwoqigYkGGIrZenjYogHAaQjYjgEPKArYjEgIlEbEYkB4bYoaQLZEbEkA4bTEbEbZGLYjZhKIbYkEoMPGAgrkhj/DF4jZiAgYvDK0R9DbogAh+bZDAYbZingECAYYAimZSCgZWm5gECWIbZjKwYqlgBW/AC38K1MP+BWpn5WpgZWCh5WmmYDCFwRW/bKBWpE4ZW/K35WqmBWpgZW/ACn//5TCFwTXjFYKFFFkiFFAEiBCK35W/K35W/AAPAK1M8K1JSDgZaCAEZSDLQZWmWIYAj+ADChgqlh5WqEwYvEAEJ9EboZWmbogAhngEIAEBREgbZlVAiyEK0qyEAEPwAgcPFUh8FQ4gAgPgjZlnhcKbEizFAD6nFbMgkGbMjSFbMjYFbMjYGLowAdfozZjPQ7ZjPQzZjbAyCjbA6CjbAyCjQI6CiQJCCiQI6CihgJIQUCBJMBKBgQUKBJgEzQNMA/greOxUDVz08MSwASh4ML5isdfBcDmArcUBkPHBYAQhi6YQKIONQThzOQTZHOMpysaVzhGQ+CsoQTZFQSR6cbdJwAJh6ThFTSuXgZDSHyRuYYCIAE+AUTbSoqUCqv8YVCXXbSZVVFan/FS0An5VoTSMDFTJFPgfwFTIrOh4qbFZsP4AqbFZn/FTofBKhIKJAC0/JY4IIADLNGn5UgAAUD/4lCFIJUhWIoABLYoA/AH4A/AH4AUA="))
};

var numerals = {
  width : 174, height : 174, bpp : 2,
  transparent : 0,
  buffer : require("heatshrink").decompress(atob("AH4A/AH4A/AH4A/AH4A/AH4Az+Aqpn4CB//AFUsPmACBgZWm58AgfAFwIAkmCtB+BWmh8PgE8F4Irl4HwFgKtnFIPAK06rBFAJWnhhXBKw8/V0CFDRgqJfhguFAAUD4anaEAgnCFwa3FfzBNEnhWInjgZgfMAogDCJwoJBKzMwJogfCbA3wA4yqSh6kED4SwDcQi+EfaQfB4AaEAgQiHcAwAQ54ZBOIgECPJBeFACE8+B4BZAgfBgfw//8CYoqVgfDDIL/DOwf/AAKEEB4gATmAZBKwbVCh4oCPghmEK6aABIwh2KKzAjCIx5WZfhIAGB55WLZwgAKB55WahhWafIgAKB55WKIx5WbHqIAoHqIAYKw/8FUM/EY3/mAUKh4qUh///4HE+EDCpfwLrZcBKxiWChjeZKxcDSwZaXFQIaMnhWCSRgAKNwRxLgYMBgf/HwQAWbBrnB4ABBFbCcMgcDBwLZYDJ0wmAuBKzEPR5qQCVrJENmCBBXxisZE4PPFwQqXN508HQKTNVjBWEbC7xB/6DMmB/BbDE//47PQLCSRFgIrpSJgA/AH4A/AH4A/AG88FVMPD738FBH/gfwFTv/FY8DQAKBeFIMwBI3AGwLLfgYjBBI6BdP4R3HFAK4IKqxWIA4M/BIwAZhgHGh//bDzREAA0DFUBMJmAqfJhMPFT8/fgIAHBJJVW/5WogbXIcRRVgcRQAWFZLiJAC5MJmArgfRDYfEJY0IADD6IhgqgUZI0IbEIJJACk/h//BZEDKzsD//8MCYAgKzwA/AH4A/AH4A/h/ADjQbNgf/+AqZhgON+EDK7QaNh8AmBWqFTJxOKzgaOmAsBACwYBOJwOBbDHwKwQcMnk8KzYuBABfDVbAnB+BHNhiBYhhYBZJxkNABZEB/6TPVrIbOh7oBVrEDTpsD4atYgcP5g7OX4KCY4BGNFIJWYDgbpNKzIcCSRpWqh/8K1A6PAH4A4h//+ApoAAIrN/7vXh4nCh4RM/gSDADHABhc8QrkwBhcDWDo4ZQLpWdJBsMQMn/AonwQMf/EokDSBgAOngHG/iuG/5eFQLYyHFYI0GQLLRJQjJOGgYRJmCBffhJgJQKysHMBiBfVjIjHURKLJAB4jGWg6LLWjwqjEJBfJWjBWH/4qggE/Z7JWQh4rpmEDFdEDaMRWIgBWp4BWpnhWpgE//4qogAqqAH4A/AH4A/AH4A/AH4A/AH4AMA"))
};

var minute = {
  width : 174, height : 174, bpp : 4,
  transparent : 1,
  buffer : require("heatshrink").decompress(atob("iIA/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A+j//+JC/ACZVB/5C/VifxiACBIn5WSiMAj6u/ACSsBgJWBV36sTLIIBCAH4AO/8QgBZBgJW/KqHxiEBj4CBK35VP/8RgERLIRW/Kh8RiERj5ZBj4ICAH5VJKgUAgMfVgRW/ABZPCgAABf4QDBWwYA/VhJVCgEEKoRgBj47vAASPBACisEAAZgCK1wuEj7jUDQJVHEgQgTADSREWgiyQVhEfBIMBK145FgJXCHJ4aGOoZZBK1qIBHZLoOfIIaHOoQnBK2yxGABUQDRJxOK0I8LK4IZWVl48CiJXKABcR+IYJVl4AC/6IBLCkfiKsKKuCvCRRhLIoKsKPIIAzLAIAIIAZPFgJUIiCsyXaJaELpISBAIQA/XZURKwvxKgJnGAH5bF+KuEgJgDAH5YMVwkBj5W/AB0fVwpWBJH6vPVwhW/VywFBI/6uQK4cBK36uRf4JXBgMfI36vSiKuBLgQA/V6HxVwJbB+JG/K6MRK4Ku/ACZSBiEBK35XU+JaCAH4ARj//AAJD/K6xC/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4AfA="))
};

var hour = {
  width : 174, height : 174, bpp : 2,
  transparent : 1,
  buffer : require("heatshrink").decompress(atob("qoA/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4Ai//VFVPXFk9/+tUqtX/4pjq/9qtAgEAFYP/A4J/hqApBAAMVrtVuoqguoqEgEBqEFWMF9P4QAFjoqf/pVFAAVXKz6rFAAcH/4qev/UEoQGBGAdX+oqhgtf///qkVA4MXQTtfFQQvB/tXPoPQbL9XqohBr/9GYf9LoLZeKoVXFQZaBKwN9BAgAYuoqCJgpWCv5WcrtAZw9XBIMF+qscqAgIuhgBj5WcVgMBuo1GKwKuBFTf1D4NdGpEFW4wAVv5LBq63HGoN/VrdfJYLXGQINVoEF/6Bb+isBJQ90uorBXAwAUOwYKHoq5Bgqtaq9QgEHQI9Qi6OCQLp1HukBv44BrrYaoEAjphHoEdrtAHBBWUQI5WBBIN1VzbYCvpWIBIKuc6BWKEwKQCHI6tTT5FX6o0BQQI5IACP1exN//oDBQQJWZq/Qi5HI/6xDKzVfq/1GxAlCuqQIACR3DABXUSBAAgr/XFVBlBVjIA/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/ADA="))
};


function draw(h,m,s) {
  g.clear();
  const m180 = 2*Math.PI/60;
  const h180 = 2*Math.PI/12;
  g.drawImage(face, 87, 87, {"rotate": (s-15)*m180});
  g.drawImage(numerals);  
  g.drawImage(minute, 87,87, {  "rotate": (m-15)*m180 });
  g.drawImage(hour, 87,87, {  "rotate": (h-3+m/60)*h180 });
}

function tick() {
  var d = new Date();
  var h= d.getHours();
  if (h>12) h = h -12;
  s = d.getSeconds();
  //ss = Date.now() % 1;
  draw(h,d.getMinutes(),s);
  if (Bangle.isBacklightOn()) {setTimeout(tick, 100);}
  else { setTimeout(tick, 1000 * (60-s)); }
}

tick();

Bangle.setUI("clock");
Bangle.on("backlight", tick);

}

/*

require("Storage").write("lektor-watch.info", {
  "id": "handdrawn",
  "name": "handdrawn",
  "src": "handdrawn.js",
  "icon": "handdrawn.img",
  "type": "clock"
  });


*/












//{"scale":1,"rotate":0});
